/// <reference types="expo/types" />

// NOTE: This file should not be edited manually. It is auto-generated by Expo.
// Commit this file to version control so TypeScript type checking works for all developers.
